### ISSUE TITLE
Scheduling Interview to a candidate

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#278]
There is no feild or flag available for a candidate to determine whether interview is scheduled or not.

For example, If a multi acount SME(DWP,NHS) scheduled a interview for a DWP Candidate. DWP admin can also schedule interview for the candidate again as he is not aware someone is already looking into this candidate.

**Comment by rkulkar5** [comment]
Issue is fixed, the changes are deployed on cloud, please test

As discussed, following changes are done
1) In the SME queue date will be shown on if Technical interview is scheduled , otherwise it will be blank
2) Technical interview can only be scheduled once, when tried to schedule again by the SAME USER it will just display alert message **"Technical interview for the candidate is already scheduled for 20-Nov-2020 "**
Otherwise if some other SME (say Sector level SME, or NHSsme) tries to schedule interview again for the same candidate, then following alert message will be displayed
**"Technical interview for the candidate is already scheduled for 20-Nov-2020 " 
            " Please write to ` DWPsme@in.ibm.com` for details."**
3) Once the Technical Interview is scheduled it can only be re-scheduled to a later DATE and TIME (both)

**Comment by Teja-swi** [comment]
Hi,

Scheduling interview seems fine. Please confirm on below query

There is no restriction like SME who scheduled interview can only initiate interview for that particular candidate.
Or any SME who has access to that candidate can initiate the interview irrespective of who scheduled

**Comment by Teja-swi** [comment]
As discussed, any SME who has access to that particular candidate can initiate interview.
